---
- hosts: all
  become: yes
  become_method: sudo
  vars_files:
    - vars/config.yml

  tasks:
    - include: tasks/houses.yml
  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted
