---
- name: Install required PHP packages for project
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - php5
    - php5-memcached
    - php5-mysql
    - libapache2-mod-php5
    - php5-imagick
    - php5-gd
    - php5-curl
  notify:
    - Restart Apache
